#!/bin/bash

# djelp assumes that you store your django projects in a certain way.
# Visit https://github.com/daggepagge/django-projects-helper for more info.

# Checking if there's no argument:
if [[ $# -eq 0 ]] ; then
    echo 'missing argument: projectname'

else
	# Moving in to the project folder:
	cd "$HOME/Development/$1/"

	# Moving in to the actual django project folder:
	cd "$1"

	# Opening the folder with finder
	open .
fi

